backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/how/index.md"
        label: "How Page"
        name: "how"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "how-page"}
          - {label: "Full_image", name: "full_image", widget: "image"}
          - {label: "Heading", name: "heading", widget: "markdown"}
          - {label: "Description", name: "description", widget: "markdown"}
          - {label: Main, name: main, widget: object, fields: [{label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}, {label: Title, name: title, widget: markdown}, {label: Subtitle, name: subtitle, widget: markdown}, {label: Description, name: description, widget: markdown}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}, {label: Title, name: title, widget: markdown}, {label: Subtitle, name: subtitle, widget: markdown}, {label: Description, name: description, widget: markdown}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}, {label: Title, name: title, widget: markdown}, {label: Subtitle, name: subtitle, widget: markdown}, {label: Description, name: description, widget: markdown}]}, {label: Image4, name: image4, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}, {label: Title, name: title, widget: markdown}, {label: Subtitle, name: subtitle, widget: markdown}, {label: Description, name: description, widget: markdown}]} ]}
      - file: "src/pages/careers/index.md"
        label: "Careers Page"
        name: "careers"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "careers-page"}
          - {label: "Full_image", name: "full_image", widget: "image"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/privacy/index.md"
        label: "Privacy Page"
        name: "privacy"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "privacy-page"}
          - {label: "Full_image", name: "full_image", widget: "image"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/who/index.md"
        label: "Who Page"
        name: "who"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "who-page"}
          - {label: "Full_image", name: "full_image", widget: "image"}
          - {label: "Heading", name: "heading", widget: "markdown"}
          - {label: "Description", name: "description", widget: "markdown"}
          - {label: Main, name: main, widget: object, fields: [{label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}, {label: Title, name: title, widget: markdown}, {label: Subtitle, name: subtitle, widget: markdown}, {label: Description, name: description, widget: markdown}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}, {label: Title, name: title, widget: markdown}, {label: Subtitle, name: subtitle, widget: markdown}, {label: Description, name: description, widget: markdown}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}, {label: Title, name: title, widget: markdown}, {label: Subtitle, name: subtitle, widget: markdown}, {label: Description, name: description, widget: markdown}]}, {label: Image4, name: image4, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}, {label: Title, name: title, widget: markdown}, {label: Subtitle, name: subtitle, widget: markdown}, {label: Description, name: description, widget: markdown}]}, {label: Image5, name: image5, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}, {label: Title, name: title, widget: markdown}, {label: Subtitle, name: subtitle, widget: markdown}, {label: Description, name: description, widget: markdown}]}, {label: Image6, name: image6, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}, {label: Title, name: title, widget: markdown}, {label: Subtitle, name: subtitle, widget: markdown}, {label: Description, name: description, widget: markdown}]} ]}
      - file: "src/pages/who/index.md"
        label: "What Page"
        name: "what"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "who-page"}
          - {label: "Full_image", name: "full_image", widget: "image"}
          - {label: "Heading", name: "heading", widget: "markdown"}
          - {label: "Description", name: "description", widget: "markdown"}
          - {label: Main, name: main, widget: object, fields: [{label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}, {label: Title, name: title, widget: markdown}, {label: Description, name: description, widget: markdown}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}, {label: Title, name: title, widget: markdown}, {label: Description, name: description, widget: markdown}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}, {label: Title, name: title, widget: markdown}, {label: Description, name: description, widget: markdown}]}, {label: Image4, name: image4, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}, {label: Title, name: title, widget: markdown}, {label: Description, name: description, widget: markdown}]}, {label: Image5, name: image5, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}, {label: Title, name: title, widget: markdown}, {label: Description, name: description, widget: markdown}]}]}
      - file: "src/pages/home/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Heading, name: heading, widget: markdown}
          - {label: Description, name: description, widget: markdown}
          - {label: Main, name: main, widget: object, fields: 
              [{label: Image1, name: image1, widget: object, fields: 
              [{label: Color, name: color, widget: native-color}, 
              {label: Image, name: image, widget: image}, 
              {label: Large Image, name: large_image, widget: image}, 
              {label: Large Image Client Title, name: large_image_client_title, widget: markdown}, 
              {label: Large Image Client Description, name: large_image_client_description, widget: markdown},
              {label: Project Team Members, name: large_image_team_members, widget: markdown}, 
              {label: Alt, name: alt, widget: string}, 
              {label: Title, name: title, widget: markdown}, 
              {label: Subtitle, name: subtitle, widget: markdown}, 
              {label: Description, name: description, widget: markdown}]}, 
              {label: Image 2, name: image2, widget: object, fields: 
              [{label: Color, name: color, widget: native-color}, 
              {label: Large Image, name: large_image, widget: image}, 
              {label: Large Image Client Title, name: large_image_client_title, widget: markdown}, 
              {label: Large Image Client Description, name: large_image_client_description, widget: markdown},
              {label: Project Team Members, name: large_image_team_members, widget: markdown}, 
              {label: Image, name: image, widget: image}, 
              {label: Alt, name: alt, widget: string}, 
              {label: Title, name: title, widget: markdown}, 
              {label: Subtitle, name: subtitle, widget: markdown}, 
              {label: Description, name: description, widget: markdown}]}, 
              {label: Image 3, name: image3, widget: object, fields: 
              [{label: Color, name: color, widget: native-color}, 
              {label: Large Image, name: large_image, widget: image}, 
              {label: Large Image Client Title, name: large_image_client_title, widget: markdown}, 
              {label: Large Image Client Description, name: large_image_client_description, widget: markdown},
              {label: Project Team Members, name: large_image_team_members, widget: markdown}, 
              {label: Image, name: image, widget: image}, 
              {label: Alt, name: alt, widget: string}, 
              {label: Title, name: title, widget: markdown}, 
              {label: SubTitle, name: subtitle, widget: markdown}, 
              {label: Description, name: description, widget: markdown}]}, 
              {label: Image 4, name: image4, widget: object, fields: 
              [{label: Color, name: color, widget: native-color}, 
              {label: Image, name: image, widget: image}, 
              {label: Large Image, name: large_image, widget: image}, 
              {label: Large Image Client Title, name: large_image_client_title, widget: markdown}, 
              {label: Large Image Client Description, name: large_image_client_description, widget: markdown},
              {label: Project Team Members, name: large_image_team_members, widget: markdown}, 
              {label: Alt, name: alt, widget: string}, 
              {label: Title, name: title, widget: markdown}, 
              {label: SubTitle, name: subtitle, widget: markdown}, 
              {label: Description, name: description, widget: markdown}]}]}
          - {label: Logos1, name: logos1, widget: markdown}
          - {label: Logos2, name: logos2, widget: markdown}
          - {label: Logos3, name: logos3, widget: markdown}
          - {label: Logos4, name: logos4, widget: markdown}